# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
Show.create!([
  {title: "Real Housewives of Beverly Hills", description: "Cameras follow affluent women (some regulars, others who recur) as they enjoy the lavish lifestyle only Beverly Hills can offer. The ladies change through the seasons and over time the cast has included former child actresses Kim and Kyle Richards, heiress Adrienne Maloof, restaurateur Lisa Vanderpump, philanthropist and business owner Taylor Armstrong and the one-time Mrs. Kelsey Grammer, Camille Donatacci (who alternates between a regular member of the cast and a recurring role during her time on the show).", time: "2019-06-18 20:00:00", channel_id: 1, viewing_locations_id: 1},
  {title: "Real Housewives of New York City", description: "This New York edition features several confident women, who change throughout the seasons as the women leave, with some returning later on. The featured ladies over time have included entrepreneur and one-time talk-show host Bethenny Frankel, part-time socialite and full-time mother Aviva Drescher (who is a cousin, by marriage, of actress Fran Drescher), best-selling author and journalist Carole Radziwill, savvy businesswoman Heather Thomson, entrepreneur Ramona Singer, sassy single mother Sonja Morgan and model Kristen Taekman.", time: "2019-06-19 20:00:00", channel_id: 1, viewing_locations_id: 1},
  {title: "Keeping Up With the Kardashians", description: "Even though things are always changing for the Kardashian family in ways they never expected, Kim, Kourtney, Khloe and the rest of the Kardashian/Jenner clan are determined to remember that family always comes first. Although the family members frequently are at odds, between siblings and their relationships, they always support one another in the end, regardless of how many controversies, and there are many. As the family's fame grows, they become more dependent on one another for support through all the highs and lows of being in the limelight.", time: "2019-06-17 20:00:00", channel_id: 2, viewing_locations_id: 1},
  {title: "Southern Charm", description: "Southern Charm reveals a world of exclusivity, money and scandal dating back through generations of families in Charleston, S.C. The docuseries follows several Charleston singles as they pursue their personal and professional lives while trying to preserve their family names because just one social faux pas can taint a family's name for generations. Featured singles include law student Craig, who helps underprivileged children who have been taken from their parents; modern Southern woman Cameran, who now works in real estate after spending 10 years in the cosmetics industry; and raconteur Shep, who is ready to tackle life's curveballs.", time: "2019-06-19 19:00:00", channel_id: 1, viewing_locations_id: 1},
  {title: "Summer House", description: "Montauk, New York, a beach town on the easternmost point of Long Island, is where affluent New Yorkers head during the summer to have a good time and get away from the stresses of city life. `Summer House' follows a group of nine friends who, after toiling away at their jobs during the week, share a house together on weekends between Memorial Day and Labour Day - America's unofficial summer season. While there, they enjoy an exclusive, high-end lifestyle that allows them to let loose. Booze-filled brunches, charity galas, bonfires and - of course - drama-filled romances are on the docket for the young professionals in their summer playground. Included in the close-knit group are life-of-the-party Kyle, who must decide whether to grow up or remain the quintessential bachelor; identical twins Ashley and Lauren, who have reached a crossroads in life; and flirtatious ex-model Carl, a newcomer to the group who has caught Lauren's eye.", time: "2019-06-16 22:00:00", channel_id: 1, viewing_locations_id: 3},
  {title: "Veep", description: "Veep follows the VP as she puts out political fires, juggles her public schedule and private life, and does everything within her limited powers to improve her dysfunctional relationship with the chief executive. Meyer's trusted -- and some not-so-trusted -- sidekicks include chief of staff Amy, one-time spokesperson Mike, and right-hand man Gary.", time: "2019-06-16 22:00:00", channel_id: 3, viewing_locations_id: 1},
  {title: "Big Little Lies", description: "Based on the same-titled best-seller by Liane Moriarty, Big Little Lies weaves a darkly comedic tale of murder and mischief in the tranquil beachfront town of Monterey, Calif. Amidst doting moms, successful husbands, beautiful children, and stunning homes exists a community fueled by rumors and divided into haves and have-nots, exposing fractured relationships between husbands and wives, parents and children, and friends and neighbors. Told through the eyes of three mothers -- Madeline, Celeste and Jane -- the series' narrative explores society's myths regarding perfection and its romanticization of marriage, sex, parenting and friendship. Reese Witherspoon, Nicole Kidman and Shailene Woodley star as the three prominent mothers of Monterey.", time: "2019-06-16 20:00:00", channel_id: 3, viewing_locations_id: 2},
  {title: "Curb Your Enthusiasm", description: "`Seinfeld' co-creator Larry David plays a version of himself on the improvised series. He faces a constant barrage of life's little annoyances, which in David's sometimes well-meaning but terminally fumbling hands don't tend to stay small for very long.", time: "2019-06-16 21:00:00", channel_id: 3, viewing_locations_id: 3}
])
Channel.create!([
  {name: "Bravo", channel_number: 237},
  {name: "E!", channel_number: 236},
  {name: "HBO", channel_number: 501},
  {name: "ABC", channel_number: 7}
])
ViewingLocation.create!([
  {location_name: "Home", location_address: "MPP"},
  {location_name: "Emily's Apartment", location_address: "Park Millenium"},
  {location_name: "Dan's Apartment", location_address: "MPP"},
  {location_name: "Sanchit's Apartment", location_address: "MPP"},
  {location_name: "Work", location_address: "MP"}
])

